name: maven spring boot ci

on:
 push:
   branches: ["main"]
jobs:
  build:
     runs-on: "ubuntu-latest"

     steps:
        - name: setup checkout
          uses: actions/checkout@v3
        - name: step 2:setup jdk
          uses: actions/setup-java@v4
          with:
           java-version: '17'
           distribution: 'zulu'
        - name: package application
          run: |
              mvn -B package --file pom.xml
              mkdir staging && cp target/*.jar staging
          
        - name: locate jar
          run: |
               cd target
               ls -a
        - name: upload artifact
          uses: actions/upload-artifact@v3
          with:
           name: myjar
           path: staging
        - name: test reports
          uses: phoenix-actions/test-reporting@v12
          with:
           name: Test Report
           path: target/surefire-reports/*.xml
           reporter: java-junit
        - name: run sonar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: sqp_14d34883bc1a3f6b76af0db5a7f8fd7400a52b0d
            SONAR_HOST_URL: https://e50e-117-205-114-168.ngrok-free.app/
            SONAR_PROJECTKEY: "maventestproject"
          run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
         
      
